name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Package with Gradle
        run: ./gradlew jar
      - name: Create Release
        run: ./gradlew publish
        env:
          PUBLISH_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
          PUBLISH_PASSWORD: ${{ secrets.REPOSITORY_TOKEN }}